# =============================================================================
# SmartFoundationTokens - Save Personal Access Token Script
# =============================================================================
# Purpose: Guide user through saving their GitHub Personal Access Token
# ==============================================================================

echo "======================================================================="
echo "1. Get Personal Access Token"
echo "========================================="
echo "========================================="
echo "========================================="
echo "========================================="
echo "========================================="
echo "========================================="
echo "========================================="
echo ""
echo "========================================="
echo "========================================="
echo ""
echo "========================================="
echo "========================================="
echo ""
echo "Step 1: Open GitHub and Generate Token"
echo "----------------------------------------"
echo "1. Open GitHub:"
echo "https://github.com/Fahad1993/SmartFoundationTokens"
echo ""
echo "Step 2: Generate Token"
echo "----------------------------------------"
echo "   a. If you're not logged in:"
echo "     i. Click 'Generate new personal access token' button"
echo "     ii. Enter your GitHub password"
echo "   iii. Click 'Authorize Fahad1993' checkbox"
echo "     iv. Copy the generated token below"
echo "      NOTE: Token expires in 90 days."
echo ""
echo "Step 2: Copy Personal Access Token"
echo "----------------------------------------"
echo "   a. Copy the token from GitHub output below:"
echo "      ```"
echo "      ghp_4w9a3p7gqv6c99x8l12z0m15y31 09"
echo "      ```"
echo "      ..."
echo "      YOUR_PERSONAL_ACCESS_TOKEN=eyJhbGciOiIzI1J7w3p7gqv6c99x8l12z0m15y31 09"
echo "      ```"
echo "      ```"
echo "      Save it somewhere safe - do not share with anyone"
echo "      This token is project-specific to your account (Fahad1993)."
echo "      "
echo "3. Close GitHub page after copying token."
echo ""
echo "========================================="
echo ""

echo "⚠️  IMPORTANT WARNING"
echo "========================================="
echo "Personal Access Tokens expire in 90 days."
echo "Plan accordingly before expiration."
echo "After expiration:"
echo "  1. Generate a NEW token"
echo " 2. Update PROJECT_TOKEN in repository secrets."
echo " 3. Rerun automation tasks from updated plan.md."
echo "========================================="
