#!/bin/bash
# ============================================================================
# SmartFoundationTickets - GitHub Token Setup Guide
# ==============================================================================

echo "========================================="
echo "GitHub Token Setup Guide"
echo "========================================="
echo ""
echo "Step 1: Get Personal Access Token"
echo ""
echo "Go to GitHub and generate a Personal Access Token"
echo ""
echo "Visit: https://github.com/Fahad1993/SmartFoundationTickets/settings/tokens"
echo ""
echo "Click: 'Generate new personal access token' button (classic: `https://docs.github.com/en/authentication/managing-personal-access-tokens`)"
echo "Copy the generated token value immediately!"
echo ""
echo ""
echo "Step 2: Save token to environment"
echo ""
echo "Save the PROJECT_TOKEN to your repository's Secrets:"
echo "  1. Go to GitHub → Settings → Tokens → Personal Access Tokens"
echo " 2. Click 'Generate new token' button"
echo " 3. Click the clipboard icon 📋"
echo "   Format: gh_pat: CLASSIC"
echo "   Value: [your personal_token_here]"
echo ""
echo "Step 3: Configure GitHub CLI"
echo ""
echo "Visit: https://docs.github.com/cli/gh-installation"
echo ""
echo "Download: gh.exe for your OS"
echo "4. Authenticate:"
echo "   gh auth login"
echo "   Enter: --pat classic:"
echo "     - your GitHub username (email) or token"
echo "   Enter your password (classic):"
echo ""
echo "5. Set PROJECT_TOKEN:"
echo "   In VS Code (upper-left corner) → Actions → Secrets"
echo "   Expand 'Secrets and variables > Actions' → Click on 'PROJECT_TOKEN'"
echo "   Click the clipboard button (right corner) to copy your token."
echo ""
echo "========================================="
